# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # Create necessary directories for images if they don't exist
      - mkdir -p _static/images/crm
      - mkdir -p _static/images/youtube-cms
      # Copy images from application directories if needed
      - cp -n applications/crm/diagrams/*.png _static/images/crm/ || true
      - cp -n applications/youtube-cms/diagrams/*.png _static/images/youtube-cms/ || true

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: conf.py
  fail_on_warning: false

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: requirements.txt

# Build documentation in additional formats such as PDF
formats:
  - htmlzip
  - pdf